### ISSUE TITLE
Incompatibility with core RC5

### ISSUE THREAD

**Issue by bluesliverx** [bluesliverx/grails-spring-security-oauth2-provider#100]
Found on #98, we seem to have some problems with the spring security core RC5 release.  We should test this out.

**Comment by bobby-vandiver** [comment]
Looks like a few things changed under the covers in the version of Spring Security that the Core plugin is using. This required updating the version of Spring OAuth we're using to the latest 2.0.7.RELEASE. I pushed a fix to master.

Please hold off on cutting a new RC of the plugin. I'd like to take a look at the other open issues and get them resolved in case there is any more work that needs to happen.
