### ISSUE TITLE
Change Access token and Refresh token validity in seconds not working

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#101]
Hi,

I'm trying to change access token validity to 60 seconds and refresh token validity to 120 seconds. I put the following properties to my config.groovy file as per documentation but with no luck:
```
grails.plugin.springsecurity.oauthProvider.tokenServices.accessTokenValiditySeconds=60
grails.plugin.springsecurity.oauthProvider.tokenServices.refreshTokenValiditySeconds=120	
grails.plugin.springsecurity.oauthProvider.defaultClientConfig.accessTokenValiditySeconds=60
grails.plugin.springsecurity.oauthProvider.defaultClientConfig.refreshTokenValiditySeconds=120
```

In my implementation I override the default token enhancer to return some additional information
```
grails.plugin.springsecurity.oauthProvider.tokenServices.tokenEnhancerBeanNames = ['userDetailsTokenEnhancer']
```

 I'm not sure if this is related. Can any one please help me fix that?

Thanks,
Feras

**Comment by bobby-vandiver** [comment]
I have not be able to reproduce this with the latest version of the plugin. What version of the plugin are you using? If possible, can you provide an example application demonstrating this issue or provide more complete instructions to reproduce this?

**Comment by bobby-vandiver** [comment]
Closing due to lack of feedback.
