### ISSUE TITLE
Authentification ok but no access to restricted urls

### ISSUE THREAD

**Issue by mariomatar** [bluesliverx/grails-spring-security-oauth2-provider#102]
Hi, 

I notice oauth is not works, I don't understand why, because authentication works but I can't access to restricted urls.

example : 

1 -
** Request
POST http://localhost:8080/myapp/oauth/token
redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fmyapp&scope=read&password=toto&username=toto&client_id=myapp&grant_type=password
** Response
{
access_token: "7957c6de-a0c5-40de-a894-ccaa188d6338"
token_type: "bearer"
refresh_token: "49740e77-c6c5-43cc-9b9d-28e61e6b0987"
expires_in: 26196
scope: "read"
}

2-
** Request
GET http://localhost:8080/myapp/admin/users?format=json
HEADER
Authorization: Bearer 7957c6de-a0c5-40de-a894-ccaa188d6338
** Response
-> Login HTML page

My config is : 

Java 8u45
Grails 2.5.0

    BuildConfig.groovy
	plugins {
		build ':tomcat:8.0.21'
		compile ':scaffolding:2.1.2'
		compile ':cache:1.1.8'
		compile ':asset-pipeline:2.2.5'
		compile ':spring-security-core:2.0-RC4'
		compile ':spring-security-facebook:0.17'
		compile ':spring-security-oauth2-provider:2.0-RC4'
		compile ':mail:1.0.7'
		compile ':quartz:1.0.2'
        }

Config.groovy

    grails {
            plugin {
                // Spring Security Core plugin
                springsecurity {
                    userLookup.userDomainClassName = 'user.User'
                    userLookup.authorityJoinClassName = 'user.UserRole'
                    authority.className = 'user.Role'
                    password.algorithm = 'bcrypt'
                    successHandler.alwaysUseDefaultTargetUrl = false
                    successHandler.useReferer = true
                    logout.postOnly = false
                    logout.redirectToReferer = true
                    auth.loginFormUrl = '/login'
                    //useSecurityEventListener = true
                    useSwitchUserFilter = true
                    debug.useFilter = true
                    roleHierarchy = '''
                       ROLE_ADMINISTRATOR > ROLE_MODERATOR
                       ROLE_ADMINISTRATOR > ROLE_MERCHANT
                       ROLE_ADMINISTRATOR > ROLE_MERCHANT_SUBSCRIPTION
                    '''
                    controllerAnnotations.staticRules = [
                        '/monitoring/**': 				  ['ROLE_ADMIN'],
                        '/stats/**': 				  	  ['ROLE_ADMIN'],
                        '/admin/**': 				      ['ROLE_ADMIN', 'ROLE_MODERATOR'],
                        '/j_spring_security_switch_user': ['ROLE_SWITCH_USER', 'IS_AUTHENTICATED_FULLY' ],
                        '/j_spring_security_exit_user':   ['permitAll'],
                        '/oauth/authorize.dispatch':      ["isFullyAuthenticated() and (request.getMethod().equals('GET') or request.getMethod().equals('POST'))"],
                        '/oauth/token.dispatch':          ["isFullyAuthenticated() and request.getMethod().equals('POST')"],
                        '/api/**':                  	  ['permitAll'],
                        '/login/**':        			  ['permitAll'],
                        '/logout/**':       			  ['permitAll'],
                        '/**/js/**':                      ['permitAll'],
                        '/**/css/**':                     ['permitAll'],
                        '/**/images/**':                  ['permitAll'],
                        '/**/favicon.ico':                ['permitAll'],
                        '/index':                         ['permitAll'],
                        '/**':                            ['permitAll']
                    ]
                    providerNames = [
                        'clientCredentialsAuthenticationProvider',
                        'facebookAuthProvider',
                        'daoAuthenticationProvider',
                        'anonymousAuthenticationProvider',
                        'rememberMeAuthenticationProvider'
                    ]
                    filterChain.chainMap = [
                        '/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
                        '/securedOAuth2Resources/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
                        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2ExceptionTranslationFilter'
                    ]
                    oauthProvider {
                        clientLookup.className = 'fr.myapp.user.oauth.Client'
                        authorizationCodeLookup.className = 'fr.myapp.user.oauth.AuthorizationCode'
                        accessTokenLookup.className = 'fr.myapp.user.oauth.AccessToken'
                        refreshTokenLookup.className = 'fr.myapp.user.oauth.RefreshToken'
                        authorization.requireScope = false
                    }
                }
            }
        }

    // Added by the Spring Security OAuth2 Provider plugin:
    grails.plugin.springsecurity.oauthProvider.clientLookup.className = fr.myapp.user.oauth.Client'
    grails.plugin.springsecurity.oauthProvider.authorizationCodeLookup.className = 'fr.myapp.user.oauth.AuthorizationCode'
    grails.plugin.springsecurity.oauthProvider.accessTokenLookup.className = 'fr.myapp.user.oauth.AccessToken'
    grails.plugin.springsecurity.oauthProvider.refreshTokenLookup.className = 'fr.myapp.user.oauth.RefreshToken'

I need your help to make this plugin works for me
Thanks

**Comment by beckje01** [comment]
In your config you have the filterChain.chainMap set up so OAuth is only being used if the url matches
`/securedOAuth2Resources/**`  

Your example URL is `http://localhost:8080/myapp/admin/users?format=json`  so it doesn't seem like you have separated out your oauth protected endpoints from the rest of your app. You may want to consider that but it isn't required.

To allow OAuth provider for all urls update your filter chain map so that the `/**` entry allows OAuth, you just need to remove the `-oauth2ProviderFilter` and `-oauth2ExceptionTranslationFilter` entries.

**Comment by mariomatar** [comment]
Great it works!
Thank you so much.

**Comment by mariomatar** [comment]
I would like to reopen this issue, 
the basic authentification from a form is not working now.
I don't know what to do

**Comment by bluesliverx** [comment]
Please make sure to walk through the setup documentation first. The basic authentication requires more configuration and is covered quite well in the docs.

**Comment by mariomatar** [comment]
Hi, 


So I follow the documentation step by step. It's not works. 
Sorry I don't understand the problem.

I'll show you what I do : 


2.1 Install Plugin
compile ":spring-security-oauth2-provider:2.0-RC4"

2.2 Create Domain Classes
grails s2-init-oauth2-provider com.myapp Client AuthorizationCode AccessToken RefreshToken

2.3 Secure Authorization and Token Endpoints
    controllerAnnotations.staticRules = [
                        '/monitoring/**': 				  ['ROLE_ADMIN'],
                        '/stats/**': 				  	  ['ROLE_ADMIN'],
                        '/admin/**': 				      ['ROLE_ADMIN', 'ROLE_MODERATOR'],
                        '/j_spring_security_switch_user': ['ROLE_SWITCH_USER', 'IS_AUTHENTICATED_FULLY' ],
                        '/j_spring_security_exit_user':   ['permitAll'],
                        '/oauth/authorize.dispatch':      ["isFullyAuthenticated() and (request.getMethod().equals('GET') or request.getMethod().equals('POST'))"],
                        '/oauth/token.dispatch':          ["isFullyAuthenticated() and request.getMethod().equals('POST')"],
                        '/api/**':                  	  ['permitAll'],
                        '/login/**':        			  ['permitAll'],
                        '/logout/**':       			  ['permitAll'],
                        '/**/js/**':                      ['permitAll'],
                        '/**/css/**':                     ['permitAll'],
                        '/**/images/**':                  ['permitAll'],
                        '/**/favicon.ico':                ['permitAll'],
                        '/index':                         ['permitAll'],
                        '/**':                            ['permitAll']
                    ]

2.4 Add Client Provider
    providerNames = [
                        'clientCredentialsAuthenticationProvider',
                        'facebookAuthProvider',
                        'daoAuthenticationProvider',
                        'anonymousAuthenticationProvider',
                        'rememberMeAuthenticationProvider'
                    ]

2.5 Exclude client_secret From Logs
grails.exceptionresolver.params.exclude = ['password', 'client_secret']

2.7 Client Registration
In BootStrap :
		def redirectUri = "www.myapp.com"
		new Client(
			clientId: 'oauthapp',
			authorizedGrantTypes: ['authorization_code', 'refresh_token', 'implicit', 'password', 'client_credentials'],
			authorities: [RoleEnum.ROLE_CLIENT],
			scopes: ['read', 'write'],
			redirectUris: [redirectUri]
		).save(flush: true)

2.8 Controlling Access to Resources
I use control access of Spring Security (@Secured(["ROLE_CLIENT"]))

The filter chains must be configured to ensure stateless access to the token endpoint and any OAuth 2.0 resources:
grails.plugin.springsecurity.filterChain.chainMap = [
        '/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
        '/securedOAuth2Resources/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2ExceptionTranslationFilter'
]
-> OK

3.3 Resource Owner Password Credentials Grant
http://localhost:8080/myapp/oauth/token?grant_type=password&client_id=oauthapp&username=my-user&password=my-password&scope=read
{
access_token: "288ab6b8-7668-46e2-9418-b62b677cd070"
token_type: "bearer"
refresh_token: "49740e77-c6c5-43cc-9b9d-28e61e6b0987"
expires_in: 42245
scope: "read"
}

In next requests I add in header Authorization: Bearer 288ab6b8-7668-46e2-9418-b62b677cd070

7 Configuration
7.1 Plugin
-> I don't know if I have to change somethings

7.2 Endpoint URLs
-> no changes

7.3 Token Services
-> no changes

7.4 Token Enhancers Configuration
-> no changes

7.5 Supported Grant Types
-> no changes

7.6 Additional Authorization Constraints
-> no changes

7.7 User Approval Configuration
-> no changes

7.8 Default Client Configuration
-> no changes

7.9 Filter Chain Configuration
-> no changes



Now I need help
Thanks
