### ISSUE TITLE
Override /oauth/token to check for token in the session

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#103]
I'm trying to implement social login in my application. I thought about saving the generated token in the session after successful authentication and then let the front end call /oauth/token to get this value from the session. How could I override the /oauth/token endpoint to include this feature? I couldn't find what  is the url mapping for this endpoint. Is there a better approach?

Thanks,
Feras

**Comment by bobby-vandiver** [comment]
The URL mapping is defined in [`SpringSecurityOauth2ProviderUrlMappings.groovy`](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/blob/master/grails-app/conf/SpringSecurityOauth2ProviderUrlMappings.groovy). You can extend the [`WrappedTokenEndpoint`](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/blob/master/src/java/grails/plugin/springsecurity/oauthprovider/endpoint/WrappedTokenEndpoint.java) and override the [`oauth2TokenEndpoint`](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/blob/master/SpringSecurityOauth2ProviderGrailsPlugin.groovy#L386) bean in your application's `resources.groovy` to make use of it.

All of that being said, the token endpoint is stateless and I would strongly recommend you expose a different endpoint or way of storing/retrieving a token from the session. But it sounds like for your use case the access token is going to serve essentially same purpose as a session identifier. Is that correct?

**Comment by bobby-vandiver** [comment]
Closing due to lack of feedback.
