### ISSUE TITLE
Null pointer exception with a Custom Authorization code token granter

### ISSUE THREAD

**Issue by xorkk** [bluesliverx/grails-spring-security-oauth2-provider#105]
Hello, 
There is a null pointer exception, when we call getOAuth2Authentication from AuthorizationCodeTokenGranter with a bad code.

when the call arrive to this.authorizationCodeServices.consumeAuthorizationCode(authorizationCode);
->  OAuth2Authentication auth = this.remove(code);
  -> GormAuthorizationCodeService -> remove(code)
     -> def gormAuthorizationCode = AuthorizationCode.findWhere((codePropertyName): code)  -> null
          ->   def serializedAuthentication = gormAuthorizationCode?."$authenticationPropertyName"
               authentication = oauth2AuthenticationSerializer.deserialize(serializedAuthentication)

Null pointer exception, So we cannot have a correct error code for this ...
I suggest to check if the gormAuthorizationCode exists before deserializing, and put a correct error message.

**Comment by bobby-vandiver** [comment]
Can you provide steps to reproduce this and/or a sample app? Also, could you provide the stacktrace for this error?

**Comment by xorkk** [comment]
oh i see there is ok in the last version. 
i was on an old version
