### ISSUE TITLE
Documentation URL Missing.

### ISSUE THREAD

**Issue by kys30** [bluesliverx/grails-spring-security-oauth2-provider#111]
Hi, 

The link to documentation for this plugin throws a 404 error. Can you please update it or send me the usage docs for this plugin .

Thanks,
Kaushik

**Comment by sofiaguyang** [comment]
The documentation source is part of the repo. Here's the link: https://github.com/bluesliverx/grails-spring-security-oauth2-provider/tree/master/spring-security-oauth2-provider/src/docs/guide

**Comment by bluesliverx** [comment]
Apparently something went wrong with publishing the docs last time, most likely related to the new grails upgrade.  I'll work on this.

**Comment by bluesliverx** [comment]
We are missing the index.html file in the main page of the docs.  We'll have to work on getting something in there that works, but for now use this link: http://bluesliverx.github.io/grails-spring-security-oauth2-provider/manual/

Note that this is for grails 3.x.  I'm working on getting the grails 2.x documentation back as well.

**Comment by bluesliverx** [comment]
The docs are fixed for 3.x
