### ISSUE TITLE
Offer OpenID Connect Provider Implementation

### ISSUE THREAD

**Issue by sofiaguyang** [bluesliverx/grails-spring-security-oauth2-provider#113]
This is a great and easy project to use. Would be even more awesome if you consider adding an OpenID Connect implementation.

**Comment by bluesliverx** [comment]
Are you looking for something like this? https://grails.org/plugin/spring-security-openid

**Comment by sofiaguyang** [comment]
To clarify, it is to have this plugin be a provider of OpenID Connect as well.

**Comment by bluesliverx** [comment]
Just making sure.  It looks like this would actually be quite difficult, at least in a spring-security world.  See https://github.com/spring-projects/spring-security-oauth/issues/220

**Comment by bobby-vandiver** [comment]
This was recently added to the open 2.1.0 milestone issues in spring-security-oauth. If the support gets added there, it should be pretty straight forward for us to incorporate it into the plugin.

**Comment by bluesliverx** [comment]
Migrated to new project
