### ISSUE TITLE
Access token additional information are being deleted when login multiple times

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#117]
Hi,
I implemented a custom user token enhancer.  This works fine for the first login attempt as I got the user details with the additional info. If I tried to login again and the token wasn't expired the additional information are being deleted and I got the user info back empty.
I'm using RC5 version. Any idea how to solve this problem?
Thanks,

**Comment by ferasodh** [comment]
I found the issue that was causing this problem. I recently changed the following:
static mapping = {
        version false
        //scope fetch:'join'//lazy: false
		//additionalInformation fetch:'join'
}
I set the fetch type to be join. Any ideas why this is happening.

**Comment by bluesliverx** [comment]
I'm not sure why that would cause issues to be honest.  Can you create a small working project that demonstrates the bug?

**Comment by bluesliverx** [comment]
Closing due to no response.  Please reopen if there is work still to be done here.
