### ISSUE TITLE
Release 3.0.0-RC2 to get #114 fix

### ISSUE THREAD

**Issue by bluesliverx** [bluesliverx/grails-spring-security-oauth2-provider#119]

**Comment by johngamarra** [comment]
+1 thanks

**Comment by bluesliverx** [comment]
3.0.0-RC2 should now be released, please reopen if you see any problems with the deployment

**Comment by davydotcom** [comment]
where is rc2?

**Comment by bluesliverx** [comment]
@davydotcom https://bintray.com/bluesliverx/grails-plugins/org.grails.plugins%3Aspring-security-oauth2-provider/3.0.0-RC2#files/org/grails/plugins/spring-security-oauth2-provider/3.0.0-RC2

**Comment by davydotcom** [comment]
odd its not showing up in grails plugin portal

**Comment by bluesliverx** [comment]
I haven't messed a lot with grails 3, so I'm not sure the plugin portal is updated anymore for the grails 3 plugins, or if they assume you will look at bintray for it.  If I need to something else to get it released on the plugin portal, let me know.

**Comment by tiagoajacobi** [comment]
Hi bluesliverx, I am facing the same problem, and I can't download the RC2 version in any repo, neither grails and bintray. where can I find it?

**Comment by bluesliverx** [comment]
@tiagoajacobi, have you tried https://bintray.com/bluesliverx/grails-plugins/org.grails.plugins%3Aspring-security-oauth2-provider/3.0.0-RC2#files/org/grails/plugins/spring-security-oauth2-provider/3.0.0-RC2?  I can see the files are there: https://bintray.com/version/files/bluesliverx/grails-plugins/org.grails.plugins%3Aspring-security-oauth2-provider/3.0.0-RC2?order=asc&sort=name&basePath=org%2Fgrails%2Fplugins%2Fspring-security-oauth2-provider%2F3.0.0-RC2&tab=files

**Comment by tiagoajacobi** [comment]
Hi @bluesliverx.

I tried, this just can't find the new version, but I could find a solution adding a new maven url.

**Comment by tiagoajacobi** [comment]
Now it's working perfectly on grails 3.1.16.
I tried to use grails 3.2.11, but I get many other problems.

Thanks

**Comment by bluesliverx** [comment]
Could you file a new issue for the other issues?
