### ISSUE TITLE
Incorrect Expiration Date being returned

### ISSUE THREAD

**Issue by himani-joshi** [bluesliverx/grails-spring-security-oauth2-provider#120]
Implementing resource owner password credentials grant.
Created a client with accessTokenValiditySeconds = 60 * 60 * 24 * 365 *50 
basically setting expiration to 50 years from today.

On getting an accessToken:

In the database the date is reflected correctly as 2066-06-30 16:52:48

However, the message returned gives 
  `
   {
      "access_token":"62add7b7-45e6-464d-9f82-ba4185781593",  
    "token_type":"bearer", 
    "refresh_token":"63c91cfe-4792-45fe-8f7d-7fd2c8ba134d", 
    "expires_in":1576797207,
    "scope":"read" }`

 "expires_in":1576797207. 
new Date(1576797207*1000) = Fri Dec 20 2019 04:43:27 GMT+0530 (IST)

Why isn't the correct date being sent back?
Also, is it possible to set unlimited/infinity so that token never expires?

**Comment by beckje01** [comment]
Expires in is the seconds from now. You need to add them to the current time. Also make sure you never store expires in since it should always be changing.

**Comment by himani-joshi** [comment]
Yes, I get that expires_in is in seconds from now. My use case is this:

The default expration period is quite small. I want an almost never-expiring kind of experience for a particular client application. So I am setting default accessTokenValiditySeconds to 50 years  ( 60 * 60 * 24 * 365 * 50 in seconds) for that client. Every accessToken generated for that client per user, is supposed to have an expires_in as 50 years from the moment of creation of that token. 

On implementing this, In the database, when I check the values, it is being reflected correctly. So today, 2016 is the year and expires_in is showing 2066 which is what I wanted. However, in the return json on oauth/token call, this same token' expires_in has 2019 as the year. I want to know why isn't the value which is in the database being shown? Why is the expires_in returned in json different from the one actually stored?

**Comment by beckje01** [comment]
So the `expires_in` is seconds from now you need to add those seconds to now ala:

```groovy
def now = new Date()
def d = ​new Date((1576797207l * 1000l) + now.getTime())
​println d
```

The reason `expires_in` is sent this way is due to the recommendation of the spec see https://tools.ietf.org/html/rfc6749#section-4.2.2

So its being returned correctly and every time you request the same token over and over you will get a different `expires_in` as it counts down.

**Comment by himani-joshi** [comment]
Okay. That clears my confusion. Thank you so much for prompt replies.

**Comment by himani-joshi** [comment]
One more thing before closing the issue. Is there a way to set configuration for a client so that its tokens never expire, unless explicitly deleted/revoked?

**Comment by bobby-vandiver** [comment]
It's possible to have a non-expiring refresh token, but an access token will always expire at some point. 

The non-expiring refresh token needs to be configured by specifying 0 or less for the client's refresh token validity property. See [here](http://bluesliverx.github.io/grails-spring-security-oauth2-provider/v3/manual/guide/domainClasses.html#refreshTokenClass) for more information.

**Comment by himani-joshi** [comment]
Alright. Thanks! :)

I have another question now. The token endpoint requires username and password(in plain text) in case of 'Resource Owner Password Credentials Grant'.

What if user is logged in, in my running application. Now inside the application I want to create a link on whose click we generate his token. 

From  springSecurityService.getCurrentUser() I can get the user object corresponding to logged in user. However, this object gives me the hashed password as it is stored by grails and that cant be used to hit the token endpoint. Since its a one way hashing, there is no way to get back plain text password from this value. 

How do I then, create token without asking user to enter his password again in some form.

**Comment by bobby-vandiver** [comment]
@himani-joshi It sounds like you should be using the Implicit or Authorization Code Grants instead of the Resource Onwer Password Credentials Grant. Since the original issue has been resolved, I am closing this. Please continue this discussion as part of issue #121 .
