### ISSUE TITLE
Unable to generate token using password grant for logged-in user 

### ISSUE THREAD

**Issue by himaniJoshi** [bluesliverx/grails-spring-security-oauth2-provider#121]
Password grant accepts username and password(in plain text):

curl -X POST -d "client_id=my-client" -d "grant_type=password" -d "username=my-user" -d "password=my-password" -d "scope=read" http://localhost:8080/oauth2-test/oauth/token

I can get user object of logged in user within my application using springSecurityService. But that object gives me hashed password as saved by grails and there is no way of getting plain-text password from it due to one-way hashing.
How can I then call this end point from within application without asking logged in user to provide his password through some form.

I posted on stackOverflow but haven't got any answer. Please help.

http://stackoverflow.com/questions/38374553/implementing-oauth2-resource-owner-password-grant-in-grails-using-plugin-within

**Comment by bobby-vandiver** [comment]
Can you explain your use case? It sounds like you just want to exchange the user's credentials for a token. If so, why is the token endpoint insufficient?

**Comment by bobby-vandiver** [comment]
It sounds like adding support to generate an access token independently of the standard OAuth flow as described in #93 would satisfy this use case. I'm closing this since the other issue captures this feature request.
