### ISSUE TITLE
Authorization Code expiry

### ISSUE THREAD

**Issue by himani-joshi** [bluesliverx/grails-spring-security-oauth2-provider#122]
Hi,

How long is the authorization code valid once generated. Is it possible to set an expiration on authorization code so as to have an OTP kind of behaviour?

If not, can we add this as a new feature?

**Comment by bobby-vandiver** [comment]
No, there currently isn't any expiration on an authorization code. It would be up to the application to remove expired authorization codes. I do agree that this would be useful for the plugin to provide out of the box, though.

**Comment by bluesliverx** [comment]
Migrated to new project
