### ISSUE TITLE
Newer versions of plugin are not available in grails plugin repos

### ISSUE THREAD

**Issue by adammontville** [bluesliverx/grails-spring-security-oauth2-provider#126]
I am following the instructions here: https://bluesliverx.github.io/grails-spring-security-oauth2-provider/v3/manual/guide/gettingStarted.html#installPlugin

Here's my running environment from `grails -version`

```
| Grails Version: 3.2.0
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_77
```

I've added `compile 'org.grails.plugins:spring-security-oauth2-provider:3.0.0-SNAPSHOT'` to the `dependencies` block in `build.gradle`, as instructed.  (NOTE: I also have `org.grails.plugins:spring-security-core:3.1.1` added to `build.gradle`.)

Here is the output I receive when running.

```
Total time: 18.559 secs
| Error Error initializing classpath: Could not find org.grails.plugins:spring-security-oauth2-provider:3.0.0-SNAPSHOT.
Searched in the following locations:
   ...
    https://repo.grails.org/grails/core/org/grails/plugins/spring-security-oauth2-provider/3.0.0-SNAPSHOT/maven-metadata.xml
    https://repo.grails.org/grails/core/org/grails/plugins/spring-security-oauth2-provider/3.0.0-SNAPSHOT/spring-security-oauth2-provider-3.0.0-SNAPSHOT.pom
    https://repo.grails.org/grails/core/org/grails/plugins/spring-security-oauth2-provider/3.0.0-SNAPSHOT/spring-security-oauth2-provider-3.0.0-SNAPSHOT.jar
```

When I try to follow one of those links, I get 404 errors; here's an example:

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Maven metadata not found for 'org/grails/plugins/spring-security-oauth2-provider/3.0.0-SNAPSHOT/maven-metadata.xml'."
  } ]
}
```

Hopefully, there's an obvious thing I have not done.  Any guidance for me?

**Comment by adammontville** [comment]
A bit more exploration gets this dependency working:

```compile 'org.grails.plugins:spring-security-oauth2-provider:3.0.0-RC1'```

Seems like the documentation should be updated.

**Comment by bobby-vandiver** [comment]
I updated the documentation. 

It looks like 3.0.0-RC2 isn't available from the main Grails plugin repository. I have to add `maven { url "http://dl.bintray.com/bluesliverx/grails-plugins" }` to my `repositories` config to pull RC2. This isn't necessary for RC1.

@bluesliverx Any idea why?

**Comment by bbooth** [comment]
Having same issue.  Thanks for the work around pointing to the bintray repo 👍

**Comment by bluesliverx** [comment]
This has been migrated to the new project.
