### ISSUE TITLE
Auto Approval doesn't seem to work

### ISSUE THREAD

**Issue by nardhar** [bluesliverx/grails-spring-security-oauth2-provider#127]
Using grails v2.5.5 and plugin v2.0-RC5 and creating a Client in Bootstrap.groovy like this

``` groovy
new Client(
    clientId: 'my-client',
    clientSecret: 'my-secret',
    authorizedGrantTypes: ['authorization_code', 'refresh_token', 'implicit', 'password', 'client_credentials'],
    authorities: ['ROLE_CLIENT'],
    scopes: ['read','write'],
    autoApproveScopes: [true],
    redirectUris: ['http://localhost:8080/my-client/oauthLogin/my-server']
).save(flush: true)
```

But when I request an authorization code, my app always sends me to the Approval page (where I can confirm or deny the client)
Am I doing something wrong? I even tried adding the default config:

``` groovy
grails.plugin.springsecurity.oauthProvider.defaultClientConfig.autoApproveScopes = [true]
```

but no success
Thanks in advance

**Comment by nardhar** [comment]
Also tried with Grails 3.2.1 and plugin version 3.0.0-RC1 (with the workaround indicated in #114) but it keeps asking for Authorization or Denial

**Comment by bobby-vandiver** [comment]
Could you provide a sample app that reproduces this issue?

**Comment by nardhar** [comment]
Thanks for the response, here I attach a Grails 3.2.1 app with the issue [SampleApp.zip](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/files/561758/SampleApp.zip)

**Comment by nardhar** [comment]
I've found that if I don't add the autoApproveScopes property and set
```groovy
grails.plugin.springsecurity.oauthProvider.defaultClientConfig.autoApproveScopes = ['true']
```
still loads the autoApproveScopes from the Client domain in this line
```groovy
return client."$propertyName" != null ? client."$propertyName" : defaultProperty
```
that is because an empty Set is different to null ```[] != null``` (true)

**Comment by bluesliverx** [comment]
@nardhar, it's not clear to me from your comments if you found a solution to the problem or if there is still an issue that needs to be fixed. If there is still an issue, please reopen and let me know so I can migrate the issue to the new project.
