### ISSUE TITLE
oAuth2 token has expired_in = 0 from time to time

### ISSUE THREAD

**Issue by koa73** [bluesliverx/grails-spring-security-oauth2-provider#128]
I'm using expires time for my tokens, which I set as 120 sec. When I've made cyclical tests by SoapUI I've found a collision,sometimes I've got expires_in=0, so token isn't valid in time when client has got it from oAuth server.

I can try to avoid this on client side, but I'd prefer to do it on server side if it's possible.

Can I set on oAuth side to present fresh token if expires_in time of current token <= 5 sec.

Tue Nov 22 18:57:52 MSK 2016:DEBUG:<< ""access_token":"109cf14c-00aa-4365-9f5f-e7a8ac815e09","token_type":"bearer","refresh_token":"2e4816c8-afdf-492d-a152-b0877080e189","**expires_in":0**,"scope":"read write"}"

**Comment by bluesliverx** [comment]
Moved to new project.
