### ISSUE TITLE
Use JWT for access tokens instead of database

### ISSUE THREAD

**Issue by EpineiroBumeran** [bluesliverx/grails-spring-security-oauth2-provider#129]
Hi,

I'm using this plugin to secure a public API and I have a doubt that I cannot find the answer in the  documentation. It's possible to use JWT to generate and store access tokens instead of GORM? This question is because using a database implies several queries to validate the access token for every request secured by the plugin, and this is a performance problem for us.
I know that spring security oauth supports JWT so it is possible?

Thanks and regards

**Comment by joemccall86** [comment]
I know it's an old comment, but I wanted to chime in.

As you alluded to this is using spring-security-oauth. So theoretically you could override the `tokenStore` bean in your `resources.groovy` to be a properly configured `JwtTokenStore`. See http://projects.spring.io/spring-security-oauth/docs/oauth2.html for the spring-specific details. You'll also need to add `spring-security-jwt` to your `build.gradle`.

**Comment by bluesliverx** [comment]
Please reopen if you feel there is still work to be done here.
