### ISSUE TITLE
how to extend client redirect uri's beyond 255 chars?

### ISSUE THREAD

**Issue by rvanderwerf** [bluesliverx/grails-spring-security-oauth2-provider#136]
I'm adding multiple redirect uri's in my client config like so:

redirectUrls = ['https://pitangui.amazon.com/spa/skill/account-linking-status.html?vendorId=xxxxxxxxxx',
								  'https://layla.amazon.com/spa/skill/account-linking-status.html?xxxxxxxxxxx',
                                  'https://layla.amazon.com/spa/skill/account-linking-status.html?vendorId=xxxxxxxxxxxxxxxxxxxx',
                                  'https://pitangui.amazon.com/spa/skill/account-linking-status.html?vendorId=xxxxxxxxxxxxxxxxxxxxx']

however I hit a 255 char limit:

Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "REDIRECT_URIS_STRING VARCHAR(255)": "'https://pitangui.amazon.com/spa/skill/account-linking-status.html?vendorId=M1M1AMAXAW4WEK,https://layla.amazon.com/spa/skill/ac... (342)"; SQL statement:
insert into client_redirect_uris (client_id, redirect_uris_string) values (?, ?) [22001-193]

but I don't see a way to control that from Client.groovy because it's making another table with another col name. I didn't see an obvious way in the source to change it any suggestions?

**Comment by bobby-vandiver** [comment]
I haven't tested this, but you should be able to tweak the `mapping` for your `Client` class to increase the column size.

Something like this:

```groovy
class Client {
    static final int MAX_REDIRECT_URI_LENGTH = 1024

    static hasMany = [
            redirectUris: String
    ]
    static hasMany = [
        redirectUris: String
    ]

    static mapping = {
        redirectUris joinTable: [column: 'REDIRECT_URIS_STRING', length: MAX_REDIRECT_URI_LENGTH]
    }
}
```

Source: http://stackoverflow.com/a/24584393/1743952

**Comment by rvanderwerf** [comment]
Thanks I will give it a try.
