### ISSUE TITLE
Grails 3.3.2 abstracted events api doesnt work when using GPARS instead of Reactor

### ISSUE THREAD

**Issue by davydotcom** [bluesliverx/grails-spring-security-oauth2-provider#144]
Grails 3.3.2 abstracted events api doesnt work when using GPARS instead of Reactor

**Comment by bluesliverx** [comment]
I didn't believe that this project uses GPARS at all.  Can you please elaborate what the problem is here?

**Comment by bluesliverx** [comment]
Please reopen if you have some concrete examples of what's going on.
