### ISSUE TITLE
better integration to spring security

### ISSUE THREAD

**Issue by FalkNisius** [bluesliverx/grails-spring-security-oauth2-provider#146]
All controllers have the spring security service included. 

With springSecurityService.getPrincipal() I get a String with the clientId and are able to collect additional information from the client.

springSecurityService.getUser() fails, because the String has no property username. It would be useful to provide a principal object, that contains the client and the username from used accessToken in the controller.

A work around with getAuthentication() gives also no access to the username of the used access token.

A second workaround, to extract the bearer token from headers by myself, ask the AccessToken DomainClass for the token and extract client and user is duplicating the most work the plugin does normally and a performance issue.

Please expose the user in authentication Object or in a principal Object.

Thanks

**Comment by bluesliverx** [comment]
Closing due to no response.  Please reopen if there is still work to be done here.
