### ISSUE TITLE
Username as incorrect clientId input for loadClientByClientId()

### ISSUE THREAD

**Issue by CybSBoss** [bluesliverx/grails-spring-security-oauth2-provider#52]
I have a small Grails test server that uses the grails-spring-security-oauth2-provider plugin. This is a Grails 2.3.4 project using the 2.0-RC1 plugin. The behavior upon submitting a request

``http://localhost:8080/test_server/oauth/authorize?response_type=code&client_id=MyClient1_0&scope=read``

to the server is not entirely correct. A breakpoint set in the `GormClientDetailsService.loadClientByClientId(String clientId)` method shows that the `clientId` sent to the method is in fact the username provided during login instead of the expected MyClient1_0. This behavior is similar to that described in a previous issue "Authentication problem using GTM OAuth? #24". 

I am unable to locate the code that is calling `loadClientByClientId()`, but I believe there is a bug in that code in which the username is substituted for the clientId (perhaps an incorrect map?)

**Comment by bobby-vandiver** [comment]
@bluesliverx  I think it's safe to close this now. It looks like after the repository got moved, I lost write access or I would close it myself. :stuck_out_tongue:

**Comment by bluesliverx** [comment]
@bobby-vandiver, whoops!  Permission granted again :)
