### ISSUE TITLE
Config in caller project is not loaded

### ISSUE THREAD

**Issue by satan1999** [bluesliverx/grails-spring-security-oauth2-provider#55]
Hi There

I recently found config in caller project is not loaded into plugin

Here is my little fix:

private static ConfigObject loadSecurityConfig(GrailsApplication app) {
        def conf = SpringSecurityUtils.securityConfig
        if (!conf || !conf.active) {
            return null
        }

        SpringSecurityUtils.loadSecondaryConfig 'DefaultOAuth2ProviderSecurityConfig'
        conf = SpringSecurityUtils.securityConfig
        conf.oauthProvider.putAll(conf.oauthProvider.utilsplugin.merge(app.config.security.oauthProvider))
        if (!conf.oauthProvider.active) {
            return null
        }
        return conf
    }

**Comment by satan1999** [comment]
The first post has the code which resolved the problem for me.

Dont know if it is useful for you

Cheers
Wallace

**Comment by bobby-vandiver** [comment]
@satan1999 I was able to get this to work following the instructions in "Programming Grails" by Burt Beckwith. The relevant section ("Partitioning Config Files") can be read via Google books [here](https://books.google.com/books?id=nvt1qQ_aU7YC&pg=PT234&lpg=PT234&dq=externalized+grails+spring+security+config&source=bl&ots=sGAU_kxs5Y&sig=dA4zkBP9kTVlgsdwlWhUG8zan_c&hl=en&sa=X&ei=tWT8VP2HJ5CHyASMUg&ved=0CDAQ6AEwAzgK#v=onepage&q=externalized%20grails%20spring%20security%20config&f=false)

In `Config.groovy` I added the following:

```groovy
grails.config.locations = [
        "classpath:external-oauth2.groovy"
]
``` 

Then I created `external-oauth2.groovy` in `src/java` so it will be on the classpath. The contents of this file:

```groovy
grails.plugin.springsecurity.oauthProvider.userApprovalEndpointUrl = "somewhere"
```

Note: you must provide the full namespace to override the configuration options. The `security` namespace used by `DefaultOAuth2ProviderSecurityConfig.groovy` takes advantage of the security config methods defined in `SpringSecurityUtils` in the Spring Security Core plugin which converts the `security` namespace into the required `grails.plugin.springsecurity` namespace.
