### ISSUE TITLE
No expiration on RefreshToken

### ISSUE THREAD

**Issue by zgarbowitz** [bluesliverx/grails-spring-security-oauth2-provider#56]
Hi,

Following the documentation, I ran s2-init-oauth2-provider. In the documentation, it indicates there should be a Date expiration field on RefreshToken for when they expire. However this field wasn't generated for me; I tried adding it manually but it was not used.

I'm wondering if this is intentional and the docs just haven't caught up? If so, how do RefreshTokens expire?

**Comment by bobby-vandiver** [comment]
What version of the plugin are you using? This was a problem that was corrected in RC2.

**Comment by zgarbowitz** [comment]
Oh ok, I'm still on RC1. I will update. I think the docs still say to set your plugin to RC1 in BuildConfig here:

http://bluesliverx.github.io/grails-spring-security-oauth2-provider/docs/guide/gettingStarted.html

The changelog does have RC2 but you might want to update that. Is the RC2 install just:

plugins {
    compile ":spring-security-oauth2-provider:2.0-RC2"
}

Thanks,
Zack

**Comment by bluesliverx** [comment]
Updated the docs, it will be updated on the site in the next doc update (or I'll just make the change manually right now).
