### ISSUE TITLE
Is it possible to use oauth provider as 2 legged oauth?

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#57]
Hi,

I would like to use your plugin as 3 legged oauth. I have clients and I don't need users to give permissions to clients. So I don't need the redirection part? Is this possible with your plugin? 

Thanks,
Feras

**Comment by bluesliverx** [comment]
Your subject says 2 legged, but the message says 3 legged, so I'm not sure which you're trying to do.  In OAuth2, you refer to different flows and not how many legs for the auth, but I believe the 3 legged OAuth1 corresponds pretty well to the `client_credentials` grant type.  2 legged OAuth 1.0 can be achieved through another flow I believe.  See [this thread](http://www.ietf.org/mail-archive/web/oauth/current/msg07957.html) and [this thread](http://www.ietf.org/mail-archive/web/oauth/current/msg06218.html) for more information on how you might do this.

This plugin implements OAuth 2.0, so any of the flows (grant types) are available.

**Comment by ferasodh** [comment]
Sorry, this was a typo. I mean 2 legged oauth. How can I use client api key and user id and password for accessing resource using OAuth 2? Which grant type should I use?

Thanks,
Feras

**Comment by bluesliverx** [comment]
I haven't read up much on 2 legged oauth 1, so I'm not sure off the top of my head.  I would recommend reading some simple tutorials on the different OAuth 2 grant types to get an idea of how they work, as you will likely find one that fits your situation.  See [here](https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified) for an example of one (didn't read through it, but it was the first google hit for oauth 2 grant types).

**Comment by ferasodh** [comment]
Yes this really helps I think I should use  grant_type=password as tutorial suggests. This is what I was looking for.By the way I have some problems setting your plugin up should I ask it here or open a new thread?

Thanks

**Comment by bluesliverx** [comment]
Open up a new thread please.  Glad to hear you found what you needed.
