### ISSUE TITLE
Problem Setting Up OAuth2-provider

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#58]
I'm trying to install oauth2-provider plugin following the docs but I have the following issues:
1- when I  run s2-init-oauth2-provider command I get that script is not found.
2- I can't find any of project classes like Client class even the plugin is installed and I can see it under project plugins.

Here is my setup:
compile ":spring-security-oauth2-provider:2.0-RC1"
compile ':spring-security-core:2.0-RC3'

Thanks,
Feras

**Comment by bluesliverx** [comment]
Use 2.0-RC2, that should solve your problem.
