### ISSUE TITLE
Integrate OAuth2 provider with Spring Security ACL plugin

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#59]
Is it possible to integrate Spring Security ACL plugin with OAuth2 plugin http://grails-plugins.github.io/grails-spring-security-acl/docs/manual/guide/usage.html ? I'm interested in securing my service using ACL plugin and using its annotations like this one @PreAuthorize("hasPermission(#id, 'com.yourapp.Report', read) or " + "hasPermission(#id, 'com.yourapp.Report', admin)")

Thanks,
Feras

**Comment by bobby-vandiver** [comment]
I briefly took a look at the ACL plugin a few months ago, but it had not been updated to work with the Spring Security Core 2.x plugin so I didn't spend any more time with it. That being said, so long as the ACL plugin isn't doing anything *really* crazy, you shouldn't have any problems using the OAuth2 provider plugin with it or any of the other Spring Security plugins.

**Comment by bluesliverx** [comment]
Not much to add, but I agree that it *should* just work.  Let us know if there's a problem and we can take a look.  Mind if close this ticket for housekeeping purposes?

**Comment by ferasodh** [comment]
No this is good. If I have any issue I'll post a new one.

Thanks

**Comment by bluesliverx** [comment]
Thanks.
