### ISSUE TITLE
The Requested Resource is Not Available Error

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#60]
Hi,

I still got the requested Resource is not available error message when I tried to access any resource in my system after implementing oauth2 plugin. I can successfully get access token but and then I sent the following header with request:

Authorization: Bearer 4c23affd-97ce-455d-ac95-8633718e6e39

My method is secured with:

@Secured(["#oauth2.isUser()"])

grails.plugin.springsecurity.securityConfigType = "Annotation"
grails.plugin.springsecurity.controllerAnnotations.staticRules = [

	'/api/search*/**':     ['permitAll'],// ['IS_AUTHENTICATED_ANONYMOUSLY'],

	'/oauth/authorize.dispatch':      ["isFullyAuthenticated() and (request.getMethod().equals('GET') or request.getMethod().equals('POST'))"],
    '/oauth/token.dispatch':          ["isFullyAuthenticated() and request.getMethod().equals('POST')"],
	'/api/login*/**':['permitAll']
]

grails.plugin.springsecurity.providerNames = [
        'clientCredentialsAuthenticationProvider',
        'daoAuthenticationProvider',
        'anonymousAuthenticationProvider',
        'rememberMeAuthenticationProvider'
]

	grails.plugin.springsecurity.filterChain.chainMap = [
'/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter',
        '/securedOAuth2Resources/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter',
        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter'

	]

grails.plugin.springsecurity.oauthProvider.clients = [
    [   clientId:"myId",
        clientSecret:"mySecret"
    ]
]

What is going wrong with this code?

Thanks,
Feras

**Comment by ferasodh** [comment]
I solved this by removing -oauth2ProviderFilter from chainMap. So no what I have is:

'/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-clientCredentialsTokenEndpointFilter'

Is this the correct configuration? or there other error somewhere else?

Thanks,

**Comment by bobby-vandiver** [comment]
The `grails.plugin.springsecurity.oauthProvider.clients` option was removed from the plugin in version 2.0. You will need to create instances of the class specified by the `grails.plugin.springsecurity.oauthProvider. clientLookup.className` configuration option.

The `oauth2ProviderFilter` is the filter that is responsible for extracting the token from the incoming request and authenticating it. Without this filter, the token in the `Authorization` header will not be checked.

You'll want to make sure you review the [Filter Chain Configuration](http://bluesliverx.github.io/grails-spring-security-oauth2-provider/docs/guide/configuration.html#filterChainConfig) section of the [User Guide](http://bluesliverx.github.io/grails-spring-security-oauth2-provider/docs/guide/index.html) and also have a good understanding of how the Spring Security filter chain is used to secure your application. (See the Spring Security documentation.)

**Comment by bobby-vandiver** [comment]
The documentation covers the steps for proper configuration of the filter chain. Closing this issue.
