### ISSUE TITLE
loadClientByClientId GormClientDetailsService.groovy line 23 Fails

### ISSUE THREAD

**Issue by atrujillo68** [bluesliverx/grails-spring-security-oauth2-provider#62]
I get this error loading the client, util.JDBCExceptionReporter Invalid object name 'client_additional_information'.
errors.GrailsExceptionResolver SQLServerException occurred when processing request: [GET] /oauth/authorize
Invalid object name 'client_additional_information'.. Stacktrace follows:
org.springframework.dao.InvalidDataAccessResourceUsageException: could not initialize a collection: [com.henryschein.onlinepm.Client.additionalInformation#1]; SQL [select additional0_.AdditionalInformation as Addition1_90_0_, additional0_.additional_information_elt as additional3_0_, additional0_.additional_information_idx as additional2_0_ from client_additional_information additional0_ where additional0_.AdditionalInformation=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not initialize a collection: [com.henryschein.onlinepm.Client.additionalInformation#1]

I *can* get it to work by commented out all calls to additionalInformation. I setup up Client.groovy file using the S2InitOauth2Approval.groovy. As I understand the additionalInformation is not used by default.

Thanks for any help, as I am new to OAUTH2 and this plugin.

**Comment by bobby-vandiver** [comment]
How are you using `additionalInformation`? Could you provide the steps to reproduce this or (better) a sample application that reproduces this problem?

**Comment by atrujillo68** [comment]
I don't have a test application and found out we've modified basic Spring Security. I will close this and re-open any issues if they arise as I will be moving to a test application.
