### ISSUE TITLE
OAuth 2.0.6 upgrade

### ISSUE THREAD

**Issue by zgarbowitz** [bluesliverx/grails-spring-security-oauth2-provider#63]
Hi,

We noticed that OAuth 2.0.6 was released last week http://spring.io/blog/2015/02/02/spring-security-oauth-2-0-6-release-available-now. I'm wondering if it's possible to upgrade to this new version while using 2.0-RC2 of your plugin?

Or if not, do you know when an update might be coming out to the new version?

Thanks,
Zack

**Comment by bobby-vandiver** [comment]
I revved the version to 2.0.6.RELEASE and ran the test suite. I ran into a `NullPointerException` in `WrappedTokenEndpoint`. It looks like a [recent change](https://github.com/spring-projects/spring-security-oauth/commit/6dfee4424501744e19081277c7cc488821ca00e6) to Spring OAuth is the culprit.

I've got a WIP branch [here](https://github.com/bobby-vandiver/grails-spring-security-oauth2-provider/commit/2e583e9febcc194ca2f59c9d9ca33364ad251834), but I'm not going to push directly to master until I understand the reason `requestMethod` is ending up `null`. If someone with more Spring MVC knowledge could enlighten me, that would be great.

**Comment by zgarbowitz** [comment]
Hi,

I was just wondering if there was any progress/update on this.

Thanks,
Zack

**Comment by bobby-vandiver** [comment]
I just pushed the upgrade. Support for passing the `HttpMethod` of a request was added to Spring MVC in version 4, which is why `requestMethod` ended up `null` when running a version of Grails that uses Spring MVC 3.

**Comment by zgarbowitz** [comment]
Awesome, thank you!
