### ISSUE TITLE
Document Basic Authentication for Client Authentication

### ISSUE THREAD

**Issue by bobby-vandiver** [bluesliverx/grails-spring-security-oauth2-provider#65]
This is an undocumented feature that I tested a while back ago. To use this, the basic auth filter provided by Spring Security Core needs to be enabled and configured properly. We need to add a few test cases to exercise this functionality and document how to use it.

**Comment by dynamind** [comment]
I've been testing this today, after seeing this post on Stackoverflow: http://stackoverflow.com/questions/28436720/grails-oauth2-provider-plugin-does-not-authenticate-for-grant-type-password/29150360#29150360

I'll reproduce the relevant details of my answer (if it is received as such) here:

If you want to be able to use HTTP Basic Authentication for the client_id, you need to enable Basic Authentication in Spring Security (in Config.groovy):

    grails.plugin.springsecurity.useBasicAuth = true

*Note: This adds `basicAuthenticationFilter` and `basicExceptionTranslationFilter` to the filter chain, which you might want to remove from all paths except '/oauth/token'.*

Then you can do this, which uses the `Authorization: Basic` header:

    curl -v -X POST \
    -u my-client: \
    -d "grant_type=password" \
    -d "scope=read" \
    -d "username=my-user" \
    -d "password=my-password" http://localhost:8080/oauth2-test/oauth/token

*Note: the client in this example has no client_secret set; the proper format for Basic Authentication is `username:password`, hence the value `my-client:` (note the colon).*

**Comment by bobby-vandiver** [comment]
I started on this the other night and quickly discovered that simply enabling the basic auth isn't enough. Everything works as expected for the happy path, but attempt to use a confidential client with bad credentials and you'll be prompted to authenticate rather than receiving the expected JSON response. 

I'm not really familiar with the [`BasicAuthenticationFilter`](http://docs.spring.io/spring-security/site/docs/3.1.7.RELEASE/apidocs/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.html) that the Core plugin registers, but I suspect we might be able to add our own instance of it using the OAuth 2.0 specific `AuthenticationManager` and `AuthenticationEntryPoint` (and any other required specifics) and configure it appropriately to support basic auth for client authentication.

**Comment by dynamind** [comment]
I would guess `basicExceptionTranslationFilter` also has something to do with this.

**Comment by dynamind** [comment]
`BasicAuthenticationFilter` has a second constructor that sets the private property `ignoreFailure` to true. If true, it just proceeds down the filter chain in case of failure. 

This is how to make it work in a Grails project without touching the plugin's code. First of all, don't use the `useBasicAuth` setting for the Spring Security Core plugin, i.e.:

    grails.plugin.springsecurity.useBasicAuth = false // this is the default, but just to be clear

Define the bean using the alternative constructor that sets `ignoreFailure` to true:

**conf/resources.groovy**

    ...
    basicAuthenticationFilter(BasicAuthenticationFilter, ref('authenticationManager')) {
        authenticationDetailsSource = ref('authenticationDetailsSource')
        rememberMeServices = ref('rememberMeServices')
        credentialsCharset = 'UTF-8' // conf.basic.credentialsCharset
    }

Install the filter in its proper position:

**conf/BootStrap.groovy**

    ...
    def init = { servletContext ->
        applicationContext = servletContext.getAttribute(ApplicationAttributes.APPLICATION_CONTEXT)
        if (applicationContext.containsBean('basicAuthenticationFilter')) {
            log.debug "Registering basicAuthenticationFilter"
            SpringSecurityUtils.clientRegisterFilter 'basicAuthenticationFilter',
                    (int)(SecurityFilterPosition.BASIC_AUTH_FILTER.order)
        }
    }

Optionally remove `basicAuthenticationFilter` from paths other than `/oauth/token`:

**conf/Config.groovy**

    grails.plugin.springsecurity.filterChain.chainMap = [
        '/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,- logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
        '/v1/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-basicAuthenticationFilter,-exceptionTranslationFilter',
        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-basicAuthenticationFilter,-oauth2ExceptionTranslationFilter'
    ]

HTTP Basic authentication with correct credentials works as described in my first reply (I get an access token). Now, however, when I send the wrong credentials, I get the following reply:

    {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

This is fine, although it would be better if it stated "Bad credentials" in `error_description`.

**Comment by dynamind** [comment]
I'm working on a [fork](https://github.com/open-zimzam/grails-spring-security-oauth2-provider/commit/7253ae745059a3c8dd83b0bf864dcd96b28b6944) to get this in. I broke 55 functional tests by (temporarily) shoe-horning it into `helper.AccessTokenRequester.getAccessToken()`, taking the `client_id` and `client_secret` from the `params` Map. I'm using the existing (but unused) `requestAccessTokenWithBasicAuth()` method:

    static String getAccessToken(Map params) {
        String clientId = params.remove('client_id')
        String clientSecret = params.remove('client_secret') ?: ''

        requestAccessTokenWithBasicAuth(params, clientId, clientSecret) :

        return response.data.access_token
    }

**Comment by dynamind** [comment]
I have created a new [pull request](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/pull/80) including documentation. It registers the filter as oauthBasicAuthenticationFilter, so it shouldn't interfere with the Core plugin.

**Comment by bobby-vandiver** [comment]
This has been resolved by the work @dynamind has done recently. Closing.
