### ISSUE TITLE
Functional testing does not work in travis build

### ISSUE THREAD

**Issue by bluesliverx** [bluesliverx/grails-spring-security-oauth2-provider#66]
@bobby-vandiver, I'm not sure what about the functional testing is not working, as I'm seeing the same errors on my local machine.

**Comment by bluesliverx** [comment]
I know at least that we need to enable phantomjs to work.  However, travis docs say to use phantomjs with no explicit path, while geb forces you to use a specific path.  I'm guessing we'll need to do a 'which' on travis to see where it is installed and just depend on the explicit path for now.

**Comment by bobby-vandiver** [comment]
@bluesliverx What errors are you seeing locally? I have my `JAVA_TOOL_OPTIONS` environment set up with `phantomjs.binary.path` pointing to my local phantomjs binary. We could take a look at what the Core plugin is doing, since it also contains Geb tests and builds on Travis.

**Comment by bluesliverx** [comment]
I'm looking at this now.  Great idea on looking at spring security core, I'm tweaking the build now to match it more closely.
