### ISSUE TITLE
Requesting new access token while one is active deletes current access token

### ISSUE THREAD

**Issue by kkaminski** [bluesliverx/grails-spring-security-oauth2-provider#68]
Version: spring-security-oauth2-provider:2.0-RC2

STR:
* Request a token via ...oauth/token?scope=...
* See new token returned
* Request a second token via ...oauth/token?scope=...

EXPECTED:
* New, valid, access token

ACTUAL:
* The origin token is returned, it is removed from the DB and "invalid token" is returned upon attempt to use it.

We have a pretty straight-forward implementation of Oauth2.  Is this a bug or is there something we need to do to handle this case? 

Thanks!

**Comment by bluesliverx** [comment]
May be related to #50, or at least may be fixed by the code committed.  @kkaminski, if you get a chance to try out the code @bobby-vandiver committed for #50, can you please do so and report if it fixes the issue for you?

**Comment by kkaminski** [comment]
@bobby-vandiver It does appear to fix it, thanks for the quick response.  Will this be rolled into an official build?

**Comment by bluesliverx** [comment]
Yes, it will be soon.  I need to still test it out, but the test project is on another computer.

**Comment by bobby-vandiver** [comment]
Fix has been merged. Closing.

**Comment by bluesliverx** [comment]
I'm releasing 2.0-RC3 as I write this.  I may need to debug the travis release process as I haven't gone through it fully yet.  Worst case, you can start using -SNAPSHOT right now I believe, it should have the fix.
