### ISSUE TITLE
Error resolving plugin dependency

### ISSUE THREAD

**Issue by JohnTheBeloved** [bluesliverx/grails-spring-security-oauth2-provider#70]
I am having issues getting the Plugin receiving this error

Error Resolve error obtaining dependencies: Failed to read artifact descriptor for org.grails.plugins:spring-security-oauth2-provider:zip:2.0-RC2 (Use --stacktrace to see the full trace)

Kindly help

**Comment by JohnTheBeloved** [comment]
My

**Comment by bluesliverx** [comment]
Glad we could help ;)
