### ISSUE TITLE
Re-authentication triggers unique violation in AccessToken

### ISSUE THREAD

**Issue by dynamind** [bluesliverx/grails-spring-security-oauth2-provider#72]
I ran into this issue after updating to 2.0-RC3, and tried `client_credentials`, `password` and authorization code grant types.

The error occurs when a (successful) authentication is repeated a second time

    Validation Error(s) occurred during save():
    - Field error in object 'zimzam.oauth2.AccessToken' on field 'value': 
      rejected value [8d2f6121-677d-41cb-b27f-df2d1379110d]; 
      codes [...,unique.java.lang.String,unique]; arguments [value,class zimzam.oauth2.AccessToken,8d2f6121-677d-41cb-b27f-df2d1379110d]; 
      default message [Property [{0}] of class [{1}] with value [{2}] must be unique]
    - Field error in object 'zimzam.oauth2.AccessToken' on field 'authenticationKey': 
      rejected value [056fb80d2a3733d3b62524b7e9e31458]; 
      codes [...,unique.java.lang.String,unique]; arguments [authenticationKey,class zimzam.oauth2.AccessToken,056fb80d2a3733d3b62524b7e9e31458]; 
      default message [Property [{0}] of class [{1}] with value [{2}] must be unique]

**Update**

This apparently has a lot to do with my own implementations of `GormTokenStoreService`. I'm unwinding the issue by reverting to the plugin-provided versions (which don't match the format of my Domain classes)

**Comment by dynamind** [comment]
Turns out the solution was applying the fix for issue #50 to my own GormTokenStoreService.

**Comment by bobby-vandiver** [comment]
I'm confused how you saw this after updating to 2.0-RC3, since that incorporates the fix for issue #50. Was this a result of developing on a stale branch of the plugin or were you integrating the plugin in an application and encountered another problem? Either way, it sounds like this is resolved, so I'll close this.

**Comment by bluesliverx** [comment]
I'll make sure RC3 got deployed correctly, not sure what's going on.

**Comment by bluesliverx** [comment]
I verified that what is in the grails plugin repo for RC3 has the fix for #50.  Try cleaning out your target directory and then rerunning the application?

**Comment by dynamind** [comment]
My Domain classes are a little different from the templates (less joins, proper cascading) so I had to subclass some methods of the GormTokenStoreService class. My version didn't contain the check on existing tokens, similar to issue #50. I checked the history of the file and there I noticed the recent patch.

**Comment by bluesliverx** [comment]
Ah, that makes much more sense.  Thanks.
