### ISSUE TITLE
Access token from password grant type redirects to login page

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#74]
Hello,

I'm trying to implement oAuth2 plugin in my project and I can successfully get access token, but when I try to access resources I get redirected to login page.

My configuration: 

compile ':spring-security-core:2.0-RC4'
compile ":spring-security-oauth2-provider:2.0-RC2"
I tried RC3 also with no luck.
grails.plugin.springsecurity.providerNames = [
	'clientCredentialsAuthenticationProvider',
	'daoAuthenticationProvider',
	'anonymousAuthenticationProvider',
	'rememberMeAuthenticationProvider'
]

grails.exceptionresolver.params.exclude = ['password', 'client_secret']

// Added by the Spring Security OAuth2 Provider plugin:
grails.plugin.springsecurity.oauthProvider.clientLookup.className = 'com.oauth.Client'
grails.plugin.springsecurity.oauthProvider.authorizationCodeLookup.className = 'com.oauth.AuthorizationCode'
grails.plugin.springsecurity.oauthProvider.accessTokenLookup.className = 'com.oauth.AccessToken'
grails.plugin.springsecurity.oauthProvider.refreshTokenLookup.className = 'com.oauth.RefreshToken'

grails.plugin.springsecurity.filterChain.chainMap = [
	'/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
	'/securedOAuth2Resources/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
	'/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2ExceptionTranslationFilter'
]

grails.plugin.springsecurity.rejectIfNoRule = false
grails.plugin.springsecurity.fii.rejectPublicInvocations = true

grails.plugin.springsecurity.controllerAnnotations.staticRules = [
	'/oauth/authorize.dispatch':      ["isFullyAuthenticated() and (request.getMethod().equals('GET') or request.getMethod().equals('POST'))"],
	'/oauth/token.dispatch':          ["isFullyAuthenticated() and request.getMethod().equals('POST')"],
	

In bootstrap I put client code:

	new Client(
			clientId: 'my-client',
			authorizedGrantTypes: ['authorization_code', 'refresh_token', 'implicit', 'password', 'client_credentials'],
			authorities: ['ROLE_CLIENT'],
			scopes: ['read', 'write'],
			accessTokenValiditySeconds:100000,
			refreshTokenValiditySeconds:100000,
			redirectUris: ['http://myredirect.com']
		).save(flush: true)
		

and here is my test controller:

class TestController extends RestfulController{
	@Secured(['ROLE_SUPER_ADMIN'])
    def index() {
		respond 'hello'		
	}
}

when I access the following url I got:
http://localhost:8080/Test-Oauth/oauth/token?grant_type=password&client_id=my-client&username=admin&password=admin&scope=read
{
"access_token": "163b8f79-7d89-47d5-b5af-9693e804f7a0",
"token_type": "bearer",
"refresh_token": "656029bc-9ada-4826-84f8-07875597e496",
"expires_in": 99999,
"scope": "read"
}
but when I try to access any resource I got: 
http://localhost:8080/Test-Oauth/test/index
Header: Authorization Bearer 86e11bae-e1e2-4174-a8ad-c3a05e1e5bfa
I get redirected to login/auth page. Any idea where is the problem how can I fix it.

Thanks,

**Comment by bobby-vandiver** [comment]
Your filter chain needs to be configured properly. For accessing your resources under `test/`, you'll need:

```groovy
grails.plugin.springsecurity.filterChain.chainMap = [
        // This covers the token endpoint only
        '/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',

        // This covers OAuth 2.0 resources:
        '/test/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',

        // This is to cover all non-OAuth 2.0 resources:
        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2ExceptionTranslationFilter'
]
```

**Comment by ferasodh** [comment]
Thanks bobby you saved my day. Can you tell me why we don't add oauth2ProviderFilter to /test/**. Isn't this filter the one that checks access tokens?

**Comment by bobby-vandiver** [comment]
The `-xxxFilter` syntax is defined by the Spring Security Core plugin and is for *removing* a filter. The `oauth2ProviderFilter` is registered in the filter chain by the plugin. So in my previous example, we're *not* removing it from `/test/**` but we *are* removing it for the token endpoint and non-OAuth 2.0 resources. Hope that helps. Closing this issue.

**Comment by ferasodh** [comment]
Bobby I used the same configuration with another project but I got 401 error Unauthorized. In the debug I got this message filter.StatelessSecurityContextPersistenceFilter  - SecurityContextHolder now cleared, as request processing completed.
Can you help me figure out where is the problem.

**Comment by bobby-vandiver** [comment]
Could you provide a sample app or more detailed instructions to reproduce this?
