### ISSUE TITLE
class no found with grails 2.5.0

### ISSUE THREAD

**Issue by moniman** [bluesliverx/grails-spring-security-oauth2-provider#76]
Hi, 

With grails 2.5.0 there an error 

org.springframework.http.converter.json.MappingJacksonHttpMessageConverter
is not found 

(in SpringSecurityOauth2ProviderGrailsPlugin)

have you a plan to fix it ?

**Comment by dynamind** [comment]
I'll have a PR ready soon

**Comment by bluesliverx** [comment]
Fixed by PR #77

**Comment by bluesliverx** [comment]
@moniman, you may use the snapshot version for now after it builds on travis.  It'll probably be a bit before an RC build since we just released.

**Comment by moniman** [comment]
thank you!

**Comment by domurtag** [comment]
Just in case anyone else runs into this. If you're using Grails 2.5.0, you need to use the following plugin version 

    compile ":spring-security-oauth2-provider:2.0-SNAPSHOT"

Presumably the fix will be included in 2.0-RC4 (and above) when this version is released
