### ISSUE TITLE
Is Logout Action Implemented

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#83]
Hi,

I would like to know if logout action is already implemented or not. What is the url for logout controller? How can I implement it in case it is not implemented?

Thanks,
Feras

**Comment by bobby-vandiver** [comment]
@ferasodh, there is currently no "logout" (token revocation) functionality provided by the plugin. The rationale is that most apps will have specific requirements around how and when tokens will be revoked.

As for implementation, to effectively revoke a token, you only need to remove it from the token store. If you're using the GORM support provided by the plugin, this is as easy as:

```groovy 
AccessToken.findByValue('my-token-value').delete()
```

Hope that clarifies things. :)

**Comment by ferasodh** [comment]
Thanks bobby. This is really Helpful :)
