### ISSUE TITLE
access token header format incorrectly documented

### ISSUE THREAD

**Issue by domurtag** [bluesliverx/grails-spring-security-oauth2-provider#84]
According to [the docs](http://bluesliverx.github.io/grails-spring-security-oauth2-provider/guide/exampleFlows.html) the token should be sent in an `Authorization` header with the following value

    Bearer: 7b9a989e-3702-4621-a631-fbd1a996fc94 

But there should be no colon after `Bearer`, i.e. the following is correct

    Bearer 7b9a989e-3702-4621-a631-fbd1a996fc94

**Comment by bluesliverx** [comment]
Thanks for the fix!
