### ISSUE TITLE
customize OAuth response

### ISSUE THREAD

**Issue by domurtag** [bluesliverx/grails-spring-security-oauth2-provider#86]
The response to a successful authentication (for the authorization_code grant type) is something like:

````json
{"access_token": "d179bf70-aa40-4df9-a3e1-440e835c273a", 
"expires_in": "43199", 
"refresh_token": "879e7bd0-5e0f-48a9-b64d-f61d5665bf4e", 
"scope": "read", 
"token_type": "bearer"}
````

Is there a way to add additional properties to this response, e.g. the user's name or email address?

**Comment by dynamind** [comment]
There's probably a way to do that, but I would recommend to instead use the access token to request those details from a REST endpoint provided by you, restricted to ROLE_USER, i.e.:

    curl -H "Authorization: Bearer d179bf70-aa40-4df9-a3e1-440e835c273a" /api/v1/userProfile
    {
        "username": "the_user",
        "email": "the_user@domain.com"
    }

**Comment by donalmurtagh** [comment]
In my case I really need to add this to the OAuth response. I've had a quick look through the Spring Security OAuth2 docs, but can't see how to do it, I guess I'll keep looking - thanks.

**Comment by dynamind** [comment]
Have you looked at `additionalInformation`, it's a `Map` property of `OAuth2AccessToken`. 
You could subclass the `GormTokenStoreService` provided by the plugin and override `getAccessToken`:

    // grails-app/services/foo/GormTokenStoreService.groovy
    package foo
    class GormTokenStoreService extends grails.plugin.springsecurity.oauthprovider.GormTokenStoreService {
        @Override 
        OAuth2AccessToken getAccessToken(OAuth2Authentication authentication) {
            OAuth2AccessToken token = super.getAccessToken(authentication)
            token.additionalInformation = [:] // Do your stuff here
            return token
        }
    }

**Comment by dynamind** [comment]
You could also use a TokenEnhancer. Try your luck here: http://stackoverflow.com/questions/22072081/change-response-in-oauth2-spring

**Comment by donalmurtagh** [comment]
Overriding `GormTokenStoreService` looks perfect - thanks a lot. It might be worth adding this to the docs? I imagine it's a fairly common requirement and I couldn't find any mention of it in the SS OAuth 2 docs.

**Comment by dynamind** [comment]
Good luck! When you manage to get this to work, would you mind sharing the steps involved here? That might give us a head start on documenting this.

**Comment by donalmurtagh** [comment]
sure thing

**Comment by donalmurtagh** [comment]
I tried the following:

- Define a custom OAuth2AccessToken implementation that populates `additionalInformation`

````groovy
class CustomOAuth2AccessToken implements OAuth2AccessToken {

    @Delegate
    OAuth2AccessToken delegate

    @Override
    Map<String, Object> getAdditionalInformation() {
        [foo: 'bar']
    }
}
````

- Override `GormTokenStoreService` such that an instance of the class above is returned

class GormTokenStoreService extends grails.plugin.springsecurity.oauthprovider.GormTokenStoreService {

    @Override
    OAuth2AccessToken getAccessToken(OAuth2Authentication authentication) {
        OAuth2AccessToken token = super.getAccessToken(authentication)

        if (token) {
            token = new CustomOAuth2AccessToken(delegate: token)
        }

        log.debug "Generated access token: $token"
        return token
    }
}

However, this doesn't seem to work. The JSON that the client receives when the auth code is exchanged for access token still has the same fields as before.

**Comment by bluesliverx** [comment]
Have you verified that your version of the token store service is actually getting used?  My guess is that it's not.

You may need to be more explicit depending on your grails version as they do namespacing in plugins differently.  I would rename the class to "MyGormTokenStoreService" and then put the following in `resources.groovy`:

```
springConfig.addAlias 'tokenStore', 'myGormTokenStoreService'
```

Then you could debug or put some printlines somewhere in your code that prints the class name of the 'tokenStore' bean:

```
def tokenStore
def list() {
    println tokenStore.class.name
}
```

Just to verify that you are getting the correct bean registered as the token store.

**Comment by donalmurtagh** [comment]
@bluesliverx it seems you might be onto something, but for some reason I can't seem to replace the `tokenStore` bean in my app. I created the following service

````groovy
class UserIdTokenStoreService extends GormTokenStoreService {

    @Override
    OAuth2AccessToken getAccessToken(OAuth2Authentication authentication) {
        OAuth2AccessToken token = super.getAccessToken(authentication)

        if (token) {
            (token as DefaultOAuth2AccessToken).setAdditionalInformation([foo: 'bar'])
            log.debug "Added additional info to token: $token.additionalInformation"
        }

        return token
    }
}
````
Then defined the following in `resources.groovy`

````groovy
beans = {
    springConfig.addAlias 'tokenStore', 'userIdTokenStoreService'
}
````
Add added the following in `BootStrap.groovy`

````groovy
class BootStrap {
    def tokenStore

    def init = { servletContext ->
        println "TOKEN STORE CLASS: ${tokenStore.getClass()}"
    }
}
````
But on startup, the following is printed

> TOKEN STORE CLASS: class grails.plugin.springsecurity.oauthprovider.GormTokenStoreService$$EnhancerBySpringCGLIB$$e6dd89d4

I also tried the following in `resources.groovy`, but it didn't seem to make any difference

    tokenStore(UserIdTokenStoreService)

I've no idea why my attempts at replacing the `tokenStore` bean don't seem to be working

**Comment by donalmurtagh** [comment]
@bluesliverx thanks for the advice. I can't implement it exactly as you've described because you have to remove you can't use 

    springConfig.addAlias 'tokenStore', 'myGormTokenStoreService'

if `tokenStore` is already a bean alias. So you have to remove the alias first. I couldn't figure out how to do this is `resources.groovy`, so I did it i a post-processor instead, i.e.
````groovy
class KerpBeanFactoryPostProcessor implements BeanFactoryPostProcessor {
    @Override
    void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {

        DefaultListableBeanFactory readWriteBeanFactory = beanFactory as DefaultListableBeanFactory

        readWriteBeanFactory.removeAlias('tokenStore')
        readWriteBeanFactory.registerAlias('myTokenStoreService', 'tokenStore')
    }
}
````
However, I keep running into a problem with invalid JSON that is generated when data is added to the access token's `additionalInformation` map. I'll open a separate issue for this.

**Comment by bluesliverx** [comment]
You should be able to just override the gormTokenStoreService bean in reality, but I'm guessing plugin namespacing was getting in the way of you doing it with a typical service in your first test.  Maybe add an alias for 'gormTokenStoreService' -> 'myGormTokenStoreService'?  The post processor is an interesting idea, as well, but seems a little funny to me and I think you can get around this without it.

Can we close this ticket then?

**Comment by donalmurtagh** [comment]
> You should be able to just override the gormTokenStoreService bean in reality, but I'm guessing plugin namespacing was getting in the way of you doing it with a typical service in your first test.

I think you're right, thanks for the pointer

>  The post processor is an interesting idea, as well, but seems a little funny to me and I think you can get around this without it.

There may be a simpler way to replace the alias, but I couldn't find one.

> Can we close this ticket then?

Yes please, I've opened #87 which provides a better description of this problem
