### ISSUE TITLE
Failing for same client-id logging from different machine/client

### ISSUE THREAD

**Issue by lakshmipmandava** [bluesliverx/grails-spring-security-oauth2-provider#91]
Hi,

We logged-in from one system and successfully got the token.at the same time trying login from different system and getting the following error for additional information.

We need help on this.

       client_id: my-client
	code: LMN1WU
	Cannot cast object '{}' with class 'java.lang.String' to class 'java.util.Map'. Stacktrace follows:
	Message: Cannot cast object '{}' with class 'java.lang.String' to class 'java.util.Map'
	    Line | Method
	->>  262 | createOAuth2AccessToken in grails.plugin.springsecurity.oauthprovider.GormTokenStoreService
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
	|    203 | getAccessToken          in     ''
	|     25 | getAccessToken . . . .  in grails.plugin.springsecurity.oauthprovider.endpoint.WrappedTokenEndpoint
	|    177 | doFilter                in grails.plugin.cache.web.filter.PageFragmentCachingFilter
	|     63 | doFilter . . . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
	|     53 | doFilter                in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
	|     49 | doFilter . . . . . . .  in grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter
	|   1145 | runWorker               in java.util.concurrent.ThreadPoolExecutor
	|    615 | run . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
	^    745 | run                     in java.lang.Thread

Thanks

**Comment by bobby-vandiver** [comment]
Can you provide more information to reproduce this issue? Specifically the version of the plugin you're using and the steps to follow to recreate this. An example app demonstrating this would be even better.

**Comment by lakshmipmandava** [comment]
I'm using 2.0-SNAPSHOT installed using `grails install`. 

The error pops up when I try to authorize the same user account from a second device. Everything goes fine the first time. When I try to login from a different device, I get to the page which presents the button to authorize application. However, on clicking the authorize button, the error reported in my first post pops up.

**Comment by bobby-vandiver** [comment]
Which grant type are you using? Are you using the same client credentials from each device? What does your Config.groovy look like? I need a little more information than what you've provided to quickly reproduce this.

**Comment by lakshmipmandava** [comment]
I'm using `authorization_code` as my grant type.
I'm following your documentation for Authorization Code Grant at http://bluesliverx.github.io/grails-spring-security-oauth2-provider/guide/exampleFlows.html. For client, I'm using oauth-client project from https://github.com/domurtag/oauth-client/
My Config.groovy is as follows:

    grails.plugin.springsecurity.oauthProvider.clientLookup.className = 'com.example.Client'
    grails.plugin.springsecurity.oauthProvider.authorizationCodeLookup.className = 'com.example.AuthorizationCode'
    grails.plugin.springsecurity.oauthProvider.accessTokenLookup.className = 'com.example.AccessToken'
    grails.plugin.springsecurity.oauthProvider.refreshTokenLookup.className = 'com.example.RefreshToken'

    grails.plugin.springsecurity.controllerAnnotations.staticRules = [

        '/oauth/authorize.dispatch': ["isFullyAuthenticated() and (request.getMethod().equals('GET') or request.getMethod().equals('POST'))"],
        '/oauth/token.dispatch'    : ["isFullyAuthenticated() and request.getMethod().equals('POST')"],

        // added by Spring Security Core
        '/'                        : ['permitAll'],
        '/index'                   : ['permitAll'],
        '/index.gsp'               : ['permitAll'],
        '/assets/**'               : ['permitAll'],
        '/**/js/**'                : ['permitAll'],
        '/**/css/**'               : ['permitAll'],
        '/**/images/**'            : ['permitAll'],
        '/**/favicon.ico'          : ['permitAll'],
        "/console/**"              : ['permitAll'],
        "/plugins/console*/**"     : ['permitAll'],
        "/AdminLTE/**"             : ['permitAll']
    ]


    grails.plugin.springsecurity.providerNames = [
        'clientCredentialsAuthenticationProvider',
        'daoAuthenticationProvider',
        'anonymousAuthenticationProvider',
        'rememberMeAuthenticationProvider'
    ]

    grails.plugin.springsecurity.filterChain.chainMap = [
        '/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
        '/securedOAuth2Resources/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2ExceptionTranslationFilter'
    ]
    
My BootStarp.groovy is as follows:
   
    Client.findByClientId('my-client')?:new Client(
            clientId: 'my-client',
            authorizedGrantTypes: ['authorization_code', 'refresh_token', 'implicit', 'password', 'client_credentials'],
            authorities: ['ROLE_CLIENT'],
            scopes: ['read', 'write'],
            redirectUris: ['http://192.168.1.102:7090/oauth-client/auth/callback']
    ).save(saveArgs)

**Comment by bobby-vandiver** [comment]
I'm attempting to recreate this but so far I'm not having any luck. You mentioned that you're using the oauth-client as your client app and that you're attempting to log in from multiple devices. Could you explain this set up a bit more so I can recreate it?

What version of Grails are you using for your provider app? Is there any way possible you could provide a sample provider app demonstrating this problem?

The stacktrace points to this being the problematic line:

```groovy
token.additionalInformation = gormAccessToken."$additionalInformationPropertyName" ?: [:]
```

The stacktrace suggests that the additional information property of your access token class is returning a `String` instead of a `Map`. Did you run the `s2-init-oauth2-provider` script after installing the plugin to generate the required classes? 

You also mentioned installing the plugin via `grails install`. The correct way to install the plugin is by declaring a dependency in `BuildConfig.groovy`:

```groovy
plugins {
   compile ":spring-security-oauth2-provider:2.0-SNAPSHOT"
}
```

**Comment by lakshmipmandava** [comment]
When I generated the Classes using s2-init-oauth2-provider AccessToken doesn't have Map<String, Object> additionalInformation and i added String additionalInformation when error came.

After adding Map<String, Object> additionalInformation class working fine now with multiipule clients.
