### ISSUE TITLE
403 error when attempting token refresh

### ISSUE THREAD

**Issue by domurtag** [bluesliverx/grails-spring-security-oauth2-provider#92]
Whenever I attempt the refresh token grant I get a HTTP 403 error (Forbidden). You can reproduce this error by following these instructions

 - Start the [OAuth provider app](https://github.com/domurtag/oauth2-provider) with `grails run-app`
 - Start the [OAuth client app](https://github.com/domurtag/oauth-client) on port 9090 with `grails run-app -Dserver.port=9090`
 - On the homepage of the client app click the "OAuth Login" link. This redirects to the provider app and prompts you to login. 
 - Enter the username "me", password "password", and click the "Authorize" button in the confirmation dialog that follows. The access token issued by the provider is displayed in the browser.
 - At the bottom of the page a "Refresh Token" link is shown that will attempt to refresh the token when clicked, but this fails with a 403 error.

I've checked all of the following: 
 - Token refresh [URL and params](http://bluesliverx.github.io/grails-spring-security-oauth2-provider/guide/exampleFlows.html#refreshToken) matches the example shown in the docs
 - The Spring security rule configured for this URL matches that shown in the docs, i.e.     
`'/oauth/token.dispatch': ["isFullyAuthenticated() and request.getMethod().equals('POST')"]`
 - The OAuth client is configured (in the database) to use the `refresh_token` grant type

I read through the relevant [section of the OAuth2 spec](https://tools.ietf.org/html/rfc6749#section-6) and noticed the following discrepancies (with the plugin docs)

- It appears that the refresh token request should be a POST rather than a GET
- An `Authorization` header should be added to the request

**Comment by bobby-vandiver** [comment]
The rule associated with the `/oauth/token.dispatch'` is what is resulting in your 403. As the rule states, the token request must be a `'POST'`. Otherwise Spring Security denies access to the resource.

Since the default behavior of an anchor tag is to do a GET on the specified URL, you're being denied access. I threw together (read: copy/pasta'd code from [here](http://stackoverflow.com/questions/8398726/using-the-post-method-with-html-anchor-tags)) and was able to verify there isn't a problem with the refresh token request:

```javascript
    <g:if test="${session.accessToken}">
        <oauth:renderToken/>

        <h2>

<form id="myform" method="post" action="${grailsApplication.config.oauthProvider.baseUrl}/oauth/token?grant_type=refresh_token&refresh_token=${session.accessToken.refresh_token}&client_id=my-client&scope=read">
  <input type="hidden" name="name" value="value" /> 
    <a onclick="document.getElementById('myform').submit();">Refresh Token (submit)</a>
    </form>
        </h2>
    </g:if>
```

Hope that clarifies things!

**Comment by domurtag** [comment]
Thanks for your speedy response (as always). Perhaps [the docs](http://bluesliverx.github.io/grails-spring-security-oauth2-provider/guide/exampleFlows.html#refreshToken) need updating, because the example therein suggests that token refresh can be performed with a GET.

Also, the section of the OAuth2 RFC I linked to shows an `Authorization` header being added to the token refresh request, but based on your response, you don't think this is necessary?

I'll try out your suggestion tomorrow (I'm in the GMT timezone), and update the sample app. Thanks again, your patience is appreciated.

**Comment by bobby-vandiver** [comment]
The docs assume the reader is familiar with the OAuth2 RFC and that they have configured the plugin rules accordingly. If you wanted to support retrieving refresh tokens via an HTTP GET (which you shouldn't), the plugin can accommodate this by using a rule for the token endpoint similar to the one the documentation suggests for the authorization endpoint.

As for the `Authorization` header, that is the client credentials using basic auth. This is supported by the plugin as well thanks to the work that @dynamind has done to support this.

**Comment by donalmurtagh** [comment]
I think it's reasonable to assume that the reader of the docs is familiar with OAuth, but nonetheless I think the URL shown for token refresh is a bit misleading. Maybe it's just me, if no HTTP method is mentioned and the URL is 

    http://localhost:8080/oauth2-test/oauth/token?grant_type=refresh_token&refresh_token=269afd46-0b41-45c2-a920-7d5af8a38d56&client_id=my-client&scope=read

then I assume HTTP GET. I think the convention used in the OAuth RFC is a lot clearer, e.g.

     POST /token HTTP/1.1
     Host: server.example.com
     Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
     Content-Type: application/x-www-form-urlencoded

     grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA

Anyway, on the more important point of whether token refresh is working, you were correct, it is working. I've updated my demo client to show a (working) token refresh link.

**Comment by bobby-vandiver** [comment]
Reopening this as a reminder to update the documentation.

**Comment by bobby-vandiver** [comment]
Updated the documentation using CURL as an example for consistency with the existing HTTP Basic examples. Closing this issue.
