### ISSUE TITLE
Creating access token manually

### ISSUE THREAD

**Issue by lakshmipmandava** [bluesliverx/grails-spring-security-oauth2-provider#93]
We have a requirement that creating user from rest resource and need to provide the access token, refresh token. I tried using gormTokenStoreService coundn't able to achieve to generate access token. would like to know is there anyway to do this.

**Comment by domurtag** [comment]
I'm not sure if this helps, but I've outlined in [this issue](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/issues/89) how you can generate an authorization code programatically.

You can generate an access and refresh token from this via an [access token request](https://tools.ietf.org/html/rfc6749#section-4.1.3)

**Comment by beckje01** [comment]
I've used the implicit grant to generate the token correctly something like:

```
		AuthorizationRequest authorizationRequest = oAuth2RequestFactory.createAuthorizationRequest(["grant_type": "implicit", "client_id": clientId, "username": username, "device_id": deviceId]);
		authorizationRequest.approved = true
		TokenRequest tokenRequest = oAuth2RequestFactory.createTokenRequest(authorizationRequest, "implicit");
		OAuth2Request storedOAuth2Request = oAuth2RequestFactory.createOAuth2Request(authorizationRequest);
		OAuth2AccessToken accessToken = tokenGranter.grant("implicit", new ImplicitTokenRequest(tokenRequest, storedOAuth2Request))
```

**Comment by donalmurtagh** [comment]
@beckje01 in my example it's an authorization code that's being generated rather than an access token

**Comment by beckje01** [comment]
Yep, I thought they were looking for generating the access token directly.

**Comment by donalmurtagh** [comment]
@beckje01 I think you're right

**Comment by bobby-vandiver** [comment]
This is similar to #89. If we expose a service to handle creating authorization codes and access tokens, it might be worthwhile to go ahead and provide a way to create the other resources that we handle, if it makes sense.

**Comment by cl4rke** [comment]
+1

**Comment by bluesliverx** [comment]
I actually had need to do the same thing today, and @beckje01's code is nearly correct for me (might be on an older version):

```
			AuthorizationRequest tokenAuthorizationRequest = oauth2RequestFactory.createAuthorizationRequest([
				"grant_type": "implicit",
				"client_id" : "my-client",
				"username"  : "my-user",
				"scope"     : "my-scope"
			])
			tokenAuthorizationRequest.approved = true
			OAuth2Request storedOAuth2Request = oauth2RequestFactory.createOAuth2Request(tokenAuthorizationRequest);
			TokenRequest tokenRequest = oauth2RequestFactory.createTokenRequest(tokenAuthorizationRequest, "implicit")

			// Grant the token and return
			def token = oauth2AuthorizationEndpointTokenGranter.grant("implicit",
				new ImplicitTokenRequest(tokenRequest, storedOAuth2Request))
```

Most notable are that the services are "oauth2*" instead of "oAuth2*".

**Comment by tekkie0206** [comment]
I used @bluesliverx solution and disabled anonymousAuthenticationFilter and i get __grails.anonymous.user__ as username instead of username i provided in the request.
