### ISSUE TITLE
Integrate facebook plugin with oauth2 plugin

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#94]
Hi,
I implemented the facebook plugin and the oauth2 plugin in my project both of them are working separately now. I want to be able to login using facebook provider and return the access token from the oauth2 plugin. How could I achieve this? which provider should I implemnt or how can I get the access token what steps should I follow? 

Thanks,

**Comment by bobby-vandiver** [comment]
I'm not familiar with the Facebook plugin, but you would probably have to implement something custom that hooks into the Facebook plugin which on successful login will generate a new access token and store it using the `tokenStore` bean provided by the OAuth2 plugin. Sorry for the *really* late response!

**Comment by bluesliverx** [comment]
Closing due to no response.  Please reopen if there is work still to be done here.
