### ISSUE TITLE
Problem with Securing api with oauth2

### ISSUE THREAD

**Issue by paruchuris** [bluesliverx/grails-spring-security-oauth2-provider#95]
I'm trying to implement OAUTH2 for securing the resources. If I add valid authorization token in headers, It is validating and request is going through. If I add an invalid authorization token in header, It says `{"error":"invalid_token","error_description":"Invalid access token: cafcadscdsac"}` also fine.
If I do not add the authorization token i.e no header, the request is going through. On debugging it i got this in log.

    DEBUG authentication.BearerTokenExtractor  - Token not found in headers. Trying request parameters.
    DEBUG authentication.BearerTokenExtractor  - Token not found in request parameters.  Not an OAuth2 request.
    DEBUG authentication.OAuth2AuthenticationProcessingFilter  - No token in request, will continue chain.

My filter chain map is as below

    grails.plugin.springsecurity.filterChain.chainMap = [
        '/oauth/token': 'JOINED_FILTERS,-oauth2ProviderFilter,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
        '/api/v1/user/create/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2ExceptionTranslationFilter',
        '/api/**': 'JOINED_FILTERS,-securityContextPersistenceFilter,-logoutFilter,-rememberMeAuthenticationFilter,-exceptionTranslationFilter',
        '/**': 'JOINED_FILTERS,-statelessSecurityContextPersistenceFilter,-oauth2ProviderFilter,-clientCredentialsTokenEndpointFilter,-oauth2ExceptionTranslationFilter',
    ]

Any idea where is the problem how can I fix it.

**Comment by paruchuris** [comment]
Any update on this?

All I need to know is if there is a way to return an error message if the request does not have `Authorization: Bearer` in the header.

**Comment by bluesliverx** [comment]
When you say "the request is going through", what exactly do you mean?  If it is returning the resource without authentication/authorization, I'm guessing there is a misconfiguration in the chain map ( @bobby-vandiver would be better able to speak to that) or you do not have the correct security configuration on your controllers using spring security core annotations or request maps.

Worst case solution that probably wouldn't even be that hard: add a spring filter of your own to reject requests matching a certain URI that do not have the header.

**Comment by paruchuris** [comment]
@bluesliverx  Thanks for your reply.

I mean that the request is serving and i'm able to receive the resource return data.

**Comment by bluesliverx** [comment]
Then that sounds like you are actually not protecting resources correctly.  How are you resources secured?

(It could still be a chain map problem, have you checked what you have against the recommended configuration in the docs?).

**Comment by paruchuris** [comment]
I have secured the resources with filter chain map as per the documentation. I have posted my filter chain map in the question.

**Comment by bluesliverx** [comment]
What I'm looking for is what did you do on the controllers or with spring security to protect your resources?  i.e. Secured annotation, static configuration, request maps, etc.

**Comment by bobby-vandiver** [comment]
I've been able to reproduce this. The filter that extracts and validates the token is a no-op if the token isn't present. I'm in the process of fixing this. Nothing major. I should have something in the next day or so.

**Comment by paruchuris** [comment]
Thanks for checking up on this @bobby-vandiver . The filter is only looking for `Bearer` token and ignoring other token types.

**Comment by bobby-vandiver** [comment]
I've pushed a set of changes that should address this.

@paruchuris Can you pull in version `2.0-SNAPSHOT` (just published by Travis) and verify this resolves your issue?

**Comment by bobby-vandiver** [comment]
Closing this issue. This has been fixed in the latest release.
