### ISSUE TITLE
Service-to-service

### ISSUE THREAD

**Issue by bsideup** [bluesliverx/grails-spring-security-oauth2-provider#96]
Hi!

Is it possible to use service-to-service oauth?

Thanks!

**Comment by bluesliverx** [comment]
Can you explain the use case a little more?  Service is a very overloaded term in my experience.

**Comment by bsideup** [comment]
@bluesliverx 

I need to call some REST api method from one server application to another using OAuth as auth method (but still keep an ability to login with OAuth from front-end as well)

**Comment by bobby-vandiver** [comment]
@bsideup If I understand correctly, it sounds like what you want to use the client credentials flow for your server-to-server communication scenario and one of the other flows, e.g. implicit, to handle your front-end use case. Have you taken a look at these grant types?

**Comment by bobby-vandiver** [comment]
Closing due to lack of feedback.
