### ISSUE TITLE
Latest version causes redirect loop

### ISSUE THREAD

**Issue by davydotcom** [bluesliverx/grails-spring-security-oauth2-provider#97]
I have pages that are not oauth authenticated on my site for users to use and use spring security core. These pages are now doing a redirect loop locally i.e. `http://localhost:8080/` does a 302 back to itself. This is after upgrading from RC1 to RC4

**Comment by davydotcom** [comment]
Should note im trying both grails 2.4.4 and grails 2.5.0 and Im using interceptUrlMap for spring security

**Comment by beckje01** [comment]
We had to do the following in resources.groovy:

```
	oauth2ProviderFilter(OAuth2AuthenticationProcessingFilter) {
		authenticationEntryPoint = ref('oauth2AuthenticationEntryPoint')
		authenticationManager = ref('oauth2AuthenticationManager')	
		stateless = false
	}
```

The key seems to be the `stateless = false` but I'm not sure why exactly.

**Comment by davydotcom** [comment]
This solution works perfectly. Thanks for the help. Probably still a bug though?

**Comment by bobby-vandiver** [comment]
Could one of you provide a little more information (steps to reproduce or a sample app) to reproduce this? Did you configure your filter chain per the documentation?

**Comment by davydotcom** [comment]
Actually did manage to fix this by adding the recommended `chainMap`
