### ISSUE TITLE
Improve oauth2 provider performance

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#99]
Hello,

After profiling my web application I noticed that 1/3 of response time is on oauth2 plugin authentication part. Is there a way to improve the plugin authentication time? Is there a way to use inmemory token store and how can I use it?

Thanks,
Feras

**Comment by bobby-vandiver** [comment]
Could you provide some information on how you're determining that "1/3 of response time is on oauth2 plugin authentication"? What sort of environment are you running in? What sort of scenario are you using to collect these metrics? I've done some profiling today and I haven't seen anything alarming.

As for using an in-memory token store, you can register Spring OAuth's `InMemoryTokenStore` implementation under the bean name `tokenStore` and everything should work. I have not tested this, but I don't see any reason why this would cause issues. Other than the typical issues you'll encounter with an in-memory store.

**Comment by bobby-vandiver** [comment]
Closing due to lack of feedback.
